### PR TITLE
boards/opentitan: Build OpenTitan with target device specific parameters

### PR DESCRIPTION
**Pull request by silvestrst**
### Pull Request Overview

I think it is useful to be able to pass options to cargo from the board specific makefiles. This PR does it in a controlled way, by not getting the `CARGO_FLAGS` from the environment, but modified from within the board makefiles.

Rust features add some flexibility. In this case they serve as simple `#[cfg(feature = "sim_verilator")]`, but could be used to pull in optional dependencies.

This pull request consists of three changes:
- Opentitan `makefile` change to pass features to Cargo.
- Creates an infrastructure in the opentitan chain (`boards/opentitan`, `chips/earlgrey)` to pass requested features. It also adds a configuration file, which based on the requested feature initialises a structure with the device specific information.
- Uses the device specific data instead of the hardcoded values.

### Testing Strategy

This pull request was tested by running on the verilator with environment variable `BOARD_CONFIGURATION=sim_verilator`, and observing the expected UART output. When built for the fpga, and ran on verilator, no output was observed (expected).

### TODO or Help Wanted

- [x] Test on the FPGA or verilator.

### Documentation Updated

No updates are required?

### Formatting

- [x] Ran `make formatall`.

### CODE REVIEW

**Comment by silvestrst** [comment]
Hmm, something is clearly not right :)

**Comment by alistair23** [comment]
Maybe it would be better to just make the clock speed settable for all targets?

When running the HiFive1 executables on QEMU there are issues with clock speed as well. Some way to override the default from the command line would be useful and would apply to all platforms instead of just OT.

File: boards/opentitan/src/main.rs [hunk 1]
```diff
@@ -126,7 +126,7 @@ pub unsafe fn reset_handler() {
     // Create a shared UART channel for the console and for kernel debug.
     let uart_mux = components::console::UartMuxComponent::new(
         &ibex::uart::UART0,
-        230400,
+        ibex::uart::UART0_BAUDRATE,
```
[the remark this answers is not in the document]
Comment (silvestrst) [reply boards/opentitan/src/main.rs:129]: I think the idea was to have fast baud rate for the FPGA, and then the standard rate for the verialtor.

File: chips/ibex/src/chip.rs [hunk 2]
```diff
@@ -15,8 +15,12 @@ use crate::plic;
 use crate::timer;
 use crate::uart;
 
+#[cfg(target_device = "nexysvideo")]
 pub const CHIP_FREQ: u32 = 50_000_000;
 
+#[cfg(target_device = "verilator")]
+pub const CHIP_FREQ: u32 = 500_000;
```
[the remark this answers is not in the document]
Comment (silvestrst) [reply chips/ibex/src/chip.rs:22]: I agree. I was thinking to make a split something along the lines of what `boards/nordic` and others do. However it is slightly awkward as nexysvideo and verilator is the same Opentitan RTL. That also brings me to a separate question, whether in chips split into lowrisc and ibex is right, or should be done somewhat differently?

[the remark this answers is not in the document]
Comment (lschuermann) [reply chips/ibex/src/chip.rs:22]: > because things outside of the makefile flow end up with no `CHIP_FREQ` set

I think this is the primary issue: statements are not being generated. I think this problem can be circumvented or at least reduced by resorting to the `cfg!(...)` macro. I guess using something like this in the code should work:
```
let chip_freq =
    if cfg!(target_device = "verilator") {
        500_000
    } else {
        other_freq
    };
```

As every `if` is an expression, this forces you to provide a return value in _every_ case and shouldn't be able to cause compile errors (although you can of course deliberately panic or abort compilation in a branch). Even within runtime code, this would be inlined as to have to performance impact.

**Comment by silvestrst** [comment]
Need to rebase my changes.

**Comment by silvestrst** [comment]
I have completely refactored my change, now it uses `features`, which I think is probably most appropriate approach for this kind of change.

What I have noticed in `Makefile.common` the build line is getting very long. If this PR gets a green light, I can split it up in multiple lines in a follow-up commit.

**Comment by silvestrst** [comment]
Could someone please help me out with the error travis is getting:
`error[E0432]: unresolved import `lowrisc::device_config::DEVICE_CONFIG`

Local build seems to work without any issues.

**Comment by jon-flatley** [comment]
> Could someone please help me out with the error travis is getting:
> `error[E0432]: unresolved import lowrisc::device_config::DEVICE_CONFIG`
> 
> Local build seems to work without any issues.

I'm not sure what exactly travis is doing, but doing a `cargo build` in `chips/ibex` produces the same error. I've never used features before, so I'm not sure what is standard, but since one of the two features `device_fpga` or `device_verilator` is required would it make sense to move this under a single feature?

Something like
```
#[cfg(not(feature = "device_verilator"))]
pub const DEVICE_CONFIG: DeviceConfig = DeviceConfig {
    name: &"device_fpga",
    chip_freq: 50_000_000,
    uart_baudrate: 230400,
};

#[cfg(feature = "device_verilator")]
pub const DEVICE_CONFIG: DeviceConfig = DeviceConfig {
    name: &"device_verilator",
    chip_freq: 500_000,
    uart_baudrate: 9600,
};
```

This allows `cargo build` in `chips/ibex` to run successfully.

**Comment by silvestrst** [comment]
I see, thank you @jon-flatley , my bad - I was only looking at this from the perspective of build being triggered through `boards/opentitan`, but chips obviously can be but obviously a chip is not exclusive to a single board. Travis is building it separately, and because the `default` option is in the `boards/opentitan` .toml, none of the structures in the `device_config.rs` are compiled.

Your suggestion makes sense, but I think I will refactor my change a little to (probably) move the `default` into `chips/lowrisc/Cargo.toml`.

**Comment by alistair23** [comment]
Overall this looks fine to me, it seems pretty clear but still flexible.

**Comment by ppannuto** [comment]
I'm afraid this is going to conflict with #1771, which I _think_ is a bit more general. Can this build on top of #1771 (or should 1771 build on this)?

**Comment by vsukhoml** [comment]
> I'm afraid this is going to conflict with #1771, which I _think_ is a bit more general. Can this build on top of #1771 (or should 1771 build on this)?

i think difference is primarily in a way CARGO_FLAGS or CARGO_OPTIONS are constructed. CARGO_FLAGS allows redefinition of all flags, while CARGO_OPTIONS relies on some defaults.

I can add CARGO_OPTIONS to #1771 CARGO_FLAGS.

**Comment by silvestrst** [comment]
@ppannuto no problem, this PR is not urgent. Thank you for letting me know.

**Comment by silvestrst** [comment]
In the latest push:
* I have updated `device_config.rs` and `chips/lowrisc/Cargo.toml`. `cargo features` are a bit awkward, I have considered to skip `boards/opentitan/Cargo.toml` entirely and pass features directly to the `lowrisc` crate in `CARGO_OPTIONS`. Unfortunately there is no way to disable the default features for dependencies (can be only done for the top package when specifying through `cargo build`).

My approach is to specify additional feature in `lowrisc`, and make any explicitly chosen feature to depend on it. That way if there are no explicitly chosen features, we can pick that up and process. In this case when there are no features explicitly requested, we use `device_fpga` (can be easily changed).

This is more or less what @jon-flatley suggested, but without the need to explicitly check all of the features to figure out whether none of them are requested.

File: chips/lowrisc/src/device_config.rs [hunk 3]
```diff
@@ -0,0 +1,22 @@
+//! Device specific configuration.
+
+pub struct DeviceConfig<'a> {
```
Comment (bradjc) [inline chips/lowrisc/src/device_config.rs:3]: What is "Device" here?

File: chips/lowrisc/src/device_config.rs [hunk 4]
```diff
@@ -0,0 +1,22 @@
...
+    pub uart_baudrate: u32,
+}
+
+// This is also a default case, when no device is specified.
+#[cfg(any(feature = "device_fpga", not(feature = "device_specified")))]
+pub const DEVICE_CONFIG: DeviceConfig = DeviceConfig {
+    name: &"device_fpga",
+    chip_freq: 50_000_000,
+    uart_baudrate: 230400,
+};
```
Comment (bradjc) [inline chips/lowrisc/src/device_config.rs:15]: Aren't these `ibex` configurations? Shouldn't they be in the ibex crate?

File: boards/opentitan/Cargo.toml [hunk 5]
```diff
@@ -5,6 +5,10 @@ authors = ["Tock Project Developers <tock-dev@googlegroups.com>"]
 build = "build.rs"
 edition = "2018"
 
+[features]
+default = ["lowrisc/device_fpga"]
```
Comment (bradjc) [inline boards/opentitan/Cargo.toml:9]: What is this the default of?

File: chips/lowrisc/src/device_config.rs (hunk 4 above)
Comment (silvestrst) [reply chips/lowrisc/src/device_config.rs:15]: I think you are right, I will move it there.

File: boards/opentitan/Cargo.toml (hunk 5 above)
Comment (silvestrst) [reply boards/opentitan/Cargo.toml:9]: Actually I think this `default` is no longer needed, I will remove it.

File: chips/lowrisc/src/device_config.rs (hunk 3 above)
Comment (silvestrst) [reply chips/lowrisc/src/device_config.rs:3]: I will add description.

**Comment by silvestrst** [comment]
> I think this is pretty reasonable, but I find cargo features to be terribly confusing. Is this really the only way to have a default option?

`[default]` is always enabled, unless specifically requested to be disabled with `--no-default-features`, unfortunately you can't tell it to "ignore when any other features are explicitly requested".

The problem is that I couldn't find any way to pass `--no-default-features` to the `board/opentitan` dependencies. It can be done for the top `Cargo.toml`, but that won't propagate to the dependencies.

It would be best to not have a `[default]` and explicitly fail when no device is specified, but that would require changes to CI.

Do you find how features are used here confusing in general, or just the `device_specified` part?

File: chips/lowrisc/src/device_config.rs (hunk 3 above)
Comment (silvestrst) [reply chips/lowrisc/src/device_config.rs:3]: Done.

File: chips/lowrisc/src/device_config.rs (hunk 4 above)
Comment (silvestrst) [reply chips/lowrisc/src/device_config.rs:15]: Done.

File: boards/opentitan/Cargo.toml (hunk 5 above)
Comment (silvestrst) [reply boards/opentitan/Cargo.toml:9]: Done.

**Comment by silvestrst** [comment]
> I think this is pretty reasonable, but I find cargo features to be terribly confusing. Is this really the only way to have a default option?

I agree it's not the best, the alternative would be to obtain these values runtime like @lschuermann suggested. The problem with that is then you wouldn't be able to simply do this:
`pub const UART0_BAUDRATE: u32 = CONFIG.uart_baudrate;
`
I don't know, it would be nice if there was `#elif `kind of functionality.

Meanwhile will push what I have got now.

**Comment by bradjc** [comment]
It seems like the config file is missing?

It seems like we want one feature `ibex_hardware_configuration` that can take multiple options. Is that possible? Can we document what those options are in a cargo.toml file?

Then the config option is used in one file to setup const structures, which then other crate files can use.

**Comment by silvestrst** [comment]
Hey @bradjc , I will look into this beginning of the next week - hopefully would be able to get it over the hump. I apologize for dragging this PR out for so long. Thank you for your review!

**Comment by silvestrst** [comment]
> It seems like we want one feature ibex_hardware_configuration that can take multiple options. Is that possible?

I don't think that is possible. Cargo features don't take any additional parameters, and in general are very rigid. There is fair amount of discussion around different ways of improving Cargo "features" feature, however most of these threads and issues are stale. To name few:
https://internals.rust-lang.org/t/mutually-exclusive-feature-flags/8601
https://github.com/rust-lang/cargo/issues/2980
...

To be honest I still think that Ibex is not an appropriate name for the chip level crate, which in my opinion should be `earlgrey` (currently the only OpenTitan chip design). `Ibex` is RISCV compliant, and I am not sure in that case why there is a need for separate crate.

With this change `Ibex` is too closely coupled with `OpenTitan` board.

An alternative could be to change peripheral instantiation from compile time to runtime, and also passing configuration into `Ibex` during board initialisation.

**Comment by silvestrst** [comment]
I guess this PR is now blocked on #1997. I think when [const context control flow](https://github.com/rust-lang/rust/pull/72437) Rust upstream change propagates in the nightly toolchain, this change probably could be made more elegant.

**Comment by silvestrst** [comment]
@bradjc thank you for polishing this change, especially the documentation changes!

**Comment by silvestrst** [comment]
Thank you guys for your help with pushing this change over the hump!

**Comment by bradjc** [comment]
@ppannuto

**Comment by bradjc** [comment]
I think Pat's request was for 1.5, which is long in the past.
